language: python
python:
    - "2.7"
# command to install dependencies
services:
    - redis-server
before_script:
	- mkdir /home/travis/logs
	- touch /home/travis/img-resizer.log
install:
    - "pip install -r requirements.txt"
# command to run tests
script: "nosetests --cov-config .coveragerc  --with-coverage"
after_success: coveralls
