language: python
python:
    - "2.7"
# command to install dependencies
services:
    - redis-server
install:
    - "pip install -r requirements.txt"
before_script:
    - "mkdir -p img-resizer/resources"
    - "ls -lha /home/travis/"
    - "ls -lha /home/travis/img-resizer/resources/"
# command to run tests
script: "nosetests --cov-config .coveragerc  --with-coverage"
after_success: coveralls
